# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(644, 572)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/RI_pic.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setWindowOpacity(5.0)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color: rgb(255, 244, 248);\n"
"border-color: rgb(0, 0, 127);\n"
"font: 75 12pt \"Times New Roman\";")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.menu_tabs = QtWidgets.QTabWidget(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.menu_tabs.setFont(font)
        self.menu_tabs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menu_tabs.setStyleSheet("")
        self.menu_tabs.setObjectName("menu_tabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(170, 20, 271, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_2.addWidget(self.radioButton, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_2.addWidget(self.radioButton_2, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setGeometry(QtCore.QRect(19, 140, 271, 371))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 269, 369))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.listWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 271, 371))
        self.listWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listWidget.setObjectName("listWidget")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab)
        self.scrollArea_2.setGeometry(QtCore.QRect(340, 140, 271, 371))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 269, 369))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.listWidget_2 = QtWidgets.QListWidget(self.scrollAreaWidgetContents_2)
        self.listWidget_2.setGeometry(QtCore.QRect(0, 0, 271, 371))
        self.listWidget_2.setObjectName("listWidget_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 271, 371))
        self.textBrowser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(30, 120, 101, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(350, 120, 141, 16))
        self.label_12.setObjectName("label_12")
        self.menu_tabs.addTab(self.tab, "")
        self.onglet_info = QtWidgets.QWidget()
        self.onglet_info.setMaximumSize(QtCore.QSize(632, 528))
        self.onglet_info.setObjectName("onglet_info")
        self.line = QtWidgets.QFrame(self.onglet_info)
        self.line.setGeometry(QtCore.QRect(10, 70, 611, 441))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox_rechercheParTerme = QtWidgets.QGroupBox(self.onglet_info)
        self.groupBox_rechercheParTerme.setGeometry(QtCore.QRect(10, 90, 291, 421))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.groupBox_rechercheParTerme.setFont(font)
        self.groupBox_rechercheParTerme.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.groupBox_rechercheParTerme.setAutoFillBackground(False)
        self.groupBox_rechercheParTerme.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.groupBox_rechercheParTerme.setObjectName("groupBox_rechercheParTerme")
        self.label = QtWidgets.QLabel(self.groupBox_rechercheParTerme)
        self.label.setGeometry(QtCore.QRect(30, 60, 47, 13))
        self.label.setObjectName("label")
        self.textEdit_terme = QtWidgets.QTextEdit(self.groupBox_rechercheParTerme)
        self.textEdit_terme.setGeometry(QtCore.QRect(10, 90, 151, 41))
        self.textEdit_terme.setObjectName("textEdit_terme")
        self.ok_terme = QtWidgets.QPushButton(self.groupBox_rechercheParTerme)
        self.ok_terme.setGeometry(QtCore.QRect(210, 100, 51, 23))
        self.ok_terme.setObjectName("ok_terme")
        self.label_3 = QtWidgets.QLabel(self.groupBox_rechercheParTerme)
        self.label_3.setGeometry(QtCore.QRect(20, 170, 71, 16))
        self.label_3.setObjectName("label_3")
        self.tableWidget_rech_terme_res = QtWidgets.QTableWidget(self.groupBox_rechercheParTerme)
        self.tableWidget_rech_terme_res.setGeometry(QtCore.QRect(10, 200, 256, 211))
        self.tableWidget_rech_terme_res.setAutoFillBackground(False)
        self.tableWidget_rech_terme_res.setObjectName("tableWidget_rech_terme_res")
        self.tableWidget_rech_terme_res.setColumnCount(2)
        self.tableWidget_rech_terme_res.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_rech_terme_res.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_rech_terme_res.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_rech_terme_res.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(170, 255, 255))
        self.tableWidget_rech_terme_res.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(170, 255, 255))
        self.tableWidget_rech_terme_res.setHorizontalHeaderItem(1, item)
        self.tableWidget_rech_terme_res.horizontalHeader().setCascadingSectionResizes(False)
        self.groupBox_rechercheParDoc = QtWidgets.QGroupBox(self.onglet_info)
        self.groupBox_rechercheParDoc.setGeometry(QtCore.QRect(330, 90, 291, 421))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.groupBox_rechercheParDoc.setFont(font)
        self.groupBox_rechercheParDoc.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.groupBox_rechercheParDoc.setObjectName("groupBox_rechercheParDoc")
        self.label_2 = QtWidgets.QLabel(self.groupBox_rechercheParDoc)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 91, 16))
        self.label_2.setObjectName("label_2")
        self.textEdit_doc = QtWidgets.QTextEdit(self.groupBox_rechercheParDoc)
        self.textEdit_doc.setGeometry(QtCore.QRect(20, 90, 151, 41))
        self.textEdit_doc.setObjectName("textEdit_doc")
        self.ok_doc = QtWidgets.QPushButton(self.groupBox_rechercheParDoc)
        self.ok_doc.setGeometry(QtCore.QRect(210, 100, 51, 23))
        self.ok_doc.setObjectName("ok_doc")
        self.label_4 = QtWidgets.QLabel(self.groupBox_rechercheParDoc)
        self.label_4.setGeometry(QtCore.QRect(30, 170, 71, 16))
        self.label_4.setObjectName("label_4")
        self.tableWidget_rech_doc_res = QtWidgets.QTableWidget(self.groupBox_rechercheParDoc)
        self.tableWidget_rech_doc_res.setGeometry(QtCore.QRect(20, 200, 256, 211))
        self.tableWidget_rech_doc_res.setObjectName("tableWidget_rech_doc_res")
        self.tableWidget_rech_doc_res.setColumnCount(2)
        self.tableWidget_rech_doc_res.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_rech_doc_res.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_rech_doc_res.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_rech_doc_res.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_rech_doc_res.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_rech_doc_res.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_rech_doc_res.setItem(0, 0, item)
        self.cB_info_index = QtWidgets.QComboBox(self.onglet_info)
        self.cB_info_index.setGeometry(QtCore.QRect(238, 20, 151, 22))
        self.cB_info_index.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cB_info_index.setObjectName("cB_info_index")
        self.cB_info_index.addItem("")
        self.cB_info_index.addItem("")
        self.label_10 = QtWidgets.QLabel(self.onglet_info)
        self.label_10.setGeometry(QtCore.QRect(120, 20, 121, 20))
        self.label_10.setObjectName("label_10")
        self.menu_tabs.addTab(self.onglet_info, "")
        self.onglet_bool = QtWidgets.QWidget()
        self.onglet_bool.setObjectName("onglet_bool")
        self.label_5 = QtWidgets.QLabel(self.onglet_bool)
        self.label_5.setGeometry(QtCore.QRect(70, 40, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.textEdit = QtWidgets.QTextEdit(self.onglet_bool)
        self.textEdit.setGeometry(QtCore.QRect(150, 30, 371, 41))
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.pushButton_bool_chercher = QtWidgets.QPushButton(self.onglet_bool)
        self.pushButton_bool_chercher.setGeometry(QtCore.QRect(440, 100, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_bool_chercher.setFont(font)
        self.pushButton_bool_chercher.setObjectName("pushButton_bool_chercher")
        self.label_6 = QtWidgets.QLabel(self.onglet_bool)
        self.label_6.setGeometry(QtCore.QRect(40, 140, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.tableWidget_bool_resultat = QtWidgets.QTableWidget(self.onglet_bool)
        self.tableWidget_bool_resultat.setGeometry(QtCore.QRect(10, 180, 611, 341))
        self.tableWidget_bool_resultat.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_bool_resultat.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_bool_resultat.setColumnCount(1)
        self.tableWidget_bool_resultat.setObjectName("tableWidget_bool_resultat")
        self.tableWidget_bool_resultat.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_bool_resultat.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_bool_resultat.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_bool_resultat.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_bool_resultat.setHorizontalHeaderItem(0, item)
        self.menu_tabs.addTab(self.onglet_bool, "")
        self.onglet_vec = QtWidgets.QWidget()
        self.onglet_vec.setObjectName("onglet_vec")
        self.label_7 = QtWidgets.QLabel(self.onglet_vec)
        self.label_7.setGeometry(QtCore.QRect(30, 30, 71, 16))
        self.label_7.setObjectName("label_7")
        self.textEdit_2 = QtWidgets.QTextEdit(self.onglet_vec)
        self.textEdit_2.setGeometry(QtCore.QRect(100, 20, 351, 31))
        self.textEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_8 = QtWidgets.QLabel(self.onglet_vec)
        self.label_8.setGeometry(QtCore.QRect(30, 90, 141, 21))
        self.label_8.setObjectName("label_8")
        self.comboBox_choix_vectoriel = QtWidgets.QComboBox(self.onglet_vec)
        self.comboBox_choix_vectoriel.setGeometry(QtCore.QRect(180, 90, 131, 22))
        self.comboBox_choix_vectoriel.setStyleSheet("background-color: rgb(255, 255, 255);        ")
        self.comboBox_choix_vectoriel.setObjectName("comboBox_choix_vectoriel")
        self.comboBox_choix_vectoriel.addItem("")
        self.comboBox_choix_vectoriel.addItem("")
        self.comboBox_choix_vectoriel.addItem("")
        self.comboBox_choix_vectoriel.addItem("")
        self.pushButton_chercher_vec = QtWidgets.QPushButton(self.onglet_vec)
        self.pushButton_chercher_vec.setGeometry(QtCore.QRect(480, 20, 75, 23))
        self.pushButton_chercher_vec.setObjectName("pushButton_chercher_vec")
        self.label_9 = QtWidgets.QLabel(self.onglet_vec)
        self.label_9.setGeometry(QtCore.QRect(30, 135, 81, 21))
        self.label_9.setObjectName("label_9")
        self.tableWidget_resultat_vectoriel = QtWidgets.QTableWidget(self.onglet_vec)
        self.tableWidget_resultat_vectoriel.setGeometry(QtCore.QRect(10, 170, 611, 351))
        self.tableWidget_resultat_vectoriel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_resultat_vectoriel.setObjectName("tableWidget_resultat_vectoriel")
        self.tableWidget_resultat_vectoriel.setColumnCount(2)
        self.tableWidget_resultat_vectoriel.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_resultat_vectoriel.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_resultat_vectoriel.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_resultat_vectoriel.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_resultat_vectoriel.setHorizontalHeaderItem(1, item)
        self.menu_tabs.addTab(self.onglet_vec, "")
        self.onglet_proba = QtWidgets.QWidget()
        self.onglet_proba.setObjectName("onglet_proba")
        self.groupBox = QtWidgets.QGroupBox(self.onglet_proba)
        self.groupBox.setGeometry(QtCore.QRect(9, 9, 611, 221))
        self.groupBox.setObjectName("groupBox")
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setGeometry(QtCore.QRect(10, 50, 61, 21))
        self.label_19.setObjectName("label_19")
        self.comboBox_choix_proba = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_choix_proba.setGeometry(QtCore.QRect(90, 50, 141, 22))
        self.comboBox_choix_proba.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_choix_proba.setObjectName("comboBox_choix_proba")
        self.comboBox_choix_proba.addItem("")
        self.comboBox_choix_proba.addItem("")
        self.comboBox_choix_proba.addItem("")
        self.comboBox_choix_proba.addItem("")
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setGeometry(QtCore.QRect(10, 110, 61, 16))
        self.label_20.setObjectName("label_20")
        self.pushButton_cherche_proba = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_cherche_proba.setGeometry(QtCore.QRect(140, 150, 75, 23))
        self.pushButton_cherche_proba.setObjectName("pushButton_cherche_proba")
        self.textEdit_proba = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_proba.setGeometry(QtCore.QRect(90, 100, 221, 31))
        self.textEdit_proba.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_proba.setObjectName("textEdit_proba")
        self.label_21 = QtWidgets.QLabel(self.groupBox)
        self.label_21.setGeometry(QtCore.QRect(330, 30, 251, 21))
        self.label_21.setObjectName("label_21")
        self.tableWidget_probab_echantillon = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget_probab_echantillon.setGeometry(QtCore.QRect(330, 60, 271, 171))
        self.tableWidget_probab_echantillon.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.tableWidget_probab_echantillon.setObjectName("tableWidget_probab_echantillon")
        self.tableWidget_probab_echantillon.setColumnCount(2)
        self.tableWidget_probab_echantillon.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_probab_echantillon.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_probab_echantillon.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_probab_echantillon.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_probab_echantillon.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_probab_echantillon.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_probab_echantillon.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_probab_echantillon.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_probab_echantillon.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_probab_echantillon.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_probab_echantillon.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_probab_echantillon.setItem(3, 0, item)
        self.groupBox_2 = QtWidgets.QGroupBox(self.onglet_proba)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 320, 611, 191))
        self.groupBox_2.setObjectName("groupBox_2")
        self.tableWidget_proba_resultat = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget_proba_resultat.setGeometry(QtCore.QRect(10, 20, 591, 231))
        self.tableWidget_proba_resultat.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_proba_resultat.setObjectName("tableWidget_proba_resultat")
        self.tableWidget_proba_resultat.setColumnCount(2)
        self.tableWidget_proba_resultat.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_proba_resultat.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_proba_resultat.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_proba_resultat.setHorizontalHeaderItem(1, item)
        self.pB_proba = QtWidgets.QPushButton(self.onglet_proba)
        self.pB_proba.setGeometry(QtCore.QRect(230, 240, 161, 23))
        self.pB_proba.setObjectName("pB_proba")
        self.textEdit_Rappel = QtWidgets.QTextEdit(self.onglet_proba)
        self.textEdit_Rappel.setGeometry(QtCore.QRect(160, 280, 81, 31))
        self.textEdit_Rappel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_Rappel.setObjectName("textEdit_Rappel")
        self.textEdit_Precision = QtWidgets.QTextEdit(self.onglet_proba)
        self.textEdit_Precision.setGeometry(QtCore.QRect(480, 280, 81, 31))
        self.textEdit_Precision.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_Precision.setObjectName("textEdit_Precision")
        self.label_13 = QtWidgets.QLabel(self.onglet_proba)
        self.label_13.setGeometry(QtCore.QRect(90, 280, 61, 20))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.onglet_proba)
        self.label_14.setGeometry(QtCore.QRect(400, 280, 71, 20))
        self.label_14.setObjectName("label_14")
        self.menu_tabs.addTab(self.onglet_proba, "")
        self.gridLayout.addWidget(self.menu_tabs, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.menu_tabs.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Projet RI"))
        self.radioButton.setText(_translate("Form", "Afficher par docs"))
        self.pushButton_2.setText(_translate("Form", "Indexe pondéré"))
        self.radioButton_2.setText(_translate("Form", "Afficher par mots"))
        self.pushButton.setText(_translate("Form", "Indexe"))
        self.label_11.setText(_translate("Form", "Element choisi :"))
        self.label_12.setText(_translate("Form", "Contenu de l\'elément :"))
        self.menu_tabs.setTabText(self.menu_tabs.indexOf(self.tab), _translate("Form", "Indexation"))
        self.groupBox_rechercheParTerme.setTitle(_translate("Form", "Recherche par terme"))
        self.label.setText(_translate("Form", "Terme"))
        self.ok_terme.setText(_translate("Form", "ok"))
        self.label_3.setText(_translate("Form", "Resultats"))
        item = self.tableWidget_rech_terme_res.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget_rech_terme_res.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget_rech_terme_res.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget_rech_terme_res.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Documents"))
        item = self.tableWidget_rech_terme_res.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Poids"))
        self.groupBox_rechercheParDoc.setTitle(_translate("Form", "Recherche par document"))
        self.label_2.setText(_translate("Form", "Documenent"))
        self.ok_doc.setText(_translate("Form", "ok"))
        self.label_4.setText(_translate("Form", "Resultats"))
        item = self.tableWidget_rech_doc_res.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget_rech_doc_res.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget_rech_doc_res.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget_rech_doc_res.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Mots"))
        item = self.tableWidget_rech_doc_res.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Poids"))
        __sortingEnabled = self.tableWidget_rech_doc_res.isSortingEnabled()
        self.tableWidget_rech_doc_res.setSortingEnabled(False)
        self.tableWidget_rech_doc_res.setSortingEnabled(__sortingEnabled)
        self.cB_info_index.setItemText(0, _translate("Form", "Indexe non pondéré"))
        self.cB_info_index.setItemText(1, _translate("Form", "Indexe pondéré"))
        self.label_10.setText(_translate("Form", "Type d\'indexation : "))
        self.menu_tabs.setTabText(self.menu_tabs.indexOf(self.onglet_info), _translate("Form", "Informations"))
        self.label_5.setText(_translate("Form", "Requête"))
        self.pushButton_bool_chercher.setText(_translate("Form", "Chercher"))
        self.label_6.setText(_translate("Form", "Resultats"))
        item = self.tableWidget_bool_resultat.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget_bool_resultat.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget_bool_resultat.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget_bool_resultat.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Documents"))
        self.menu_tabs.setTabText(self.menu_tabs.indexOf(self.onglet_bool), _translate("Form", "Modèle booléen"))
        self.label_7.setText(_translate("Form", "Requête"))
        self.label_8.setText(_translate("Form", "Méthodes possibles"))
        self.comboBox_choix_vectoriel.setItemText(0, _translate("Form", "Produit interne"))
        self.comboBox_choix_vectoriel.setItemText(1, _translate("Form", "Coef de Dice"))
        self.comboBox_choix_vectoriel.setItemText(2, _translate("Form", "Cosinus"))
        self.comboBox_choix_vectoriel.setItemText(3, _translate("Form", "Jaccard"))
        self.pushButton_chercher_vec.setText(_translate("Form", "Chercher"))
        self.label_9.setText(_translate("Form", "Résultats"))
        item = self.tableWidget_resultat_vectoriel.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget_resultat_vectoriel.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget_resultat_vectoriel.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Documents"))
        item = self.tableWidget_resultat_vectoriel.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Similarité"))
        self.menu_tabs.setTabText(self.menu_tabs.indexOf(self.onglet_vec), _translate("Form", "Modèle Vectoriel"))
        self.groupBox.setTitle(_translate("Form", "Phase 1 : Construction de l\'echantillon d\'apprentissage"))
        self.label_19.setText(_translate("Form", "Méthodes :"))
        self.comboBox_choix_proba.setItemText(0, _translate("Form", "Produit interne"))
        self.comboBox_choix_proba.setItemText(1, _translate("Form", "Coef de Dice"))
        self.comboBox_choix_proba.setItemText(2, _translate("Form", "Cosinus"))
        self.comboBox_choix_proba.setItemText(3, _translate("Form", "Coef de Jaccard"))
        self.label_20.setText(_translate("Form", "Requête"))
        self.pushButton_cherche_proba.setText(_translate("Form", "Chercher"))
        self.label_21.setText(_translate("Form", "Echantillon de documents pertinents"))
        item = self.tableWidget_probab_echantillon.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget_probab_echantillon.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget_probab_echantillon.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget_probab_echantillon.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget_probab_echantillon.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Documents"))
        item = self.tableWidget_probab_echantillon.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Similarité"))
        __sortingEnabled = self.tableWidget_probab_echantillon.isSortingEnabled()
        self.tableWidget_probab_echantillon.setSortingEnabled(False)
        self.tableWidget_probab_echantillon.setSortingEnabled(__sortingEnabled)
        self.groupBox_2.setTitle(_translate("Form", "Phase 2 : Résultat de l\'évaluation"))
        item = self.tableWidget_proba_resultat.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget_proba_resultat.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Document"))
        item = self.tableWidget_proba_resultat.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Similarité"))
        self.pB_proba.setText(_translate("Form", "Recherche probabiliste"))
        self.label_13.setText(_translate("Form", "Rappel :"))
        self.label_14.setText(_translate("Form", "Précision :"))
        self.menu_tabs.setTabText(self.menu_tabs.indexOf(self.onglet_proba), _translate("Form", "Modèle probabiliste"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

